# Networking
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_DNS_RESOLVER=y

# Network shell
CONFIG_NET_SHELL=y

# Network resources
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_MAX_CONN=8
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_NET_MGMT_EVENT_STACK_SIZE=2048

# HTTP
CONFIG_HTTP_CLIENT=y

# SNTP
CONFIG_RTC=y
CONFIG_SNTP=y

# Logging
CONFIG_LOG_BACKEND_SHOW_TIMESTAMP=y
CONFIG_LOG_OUTPUT_FORMAT_DATE_TIMESTAMP=y
CONFIG_LOG_TIMESTAMP_USE_REALTIME=y
