# Networking
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_DNS_RESOLVER=y

# Network shell
CONFIG_NET_SHELL=y

# Network resources
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_MAX_CONN=8
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096

# HTTP
CONFIG_HTTP_CLIENT=y

# SNTP
CONFIG_RTC=y
CONFIG_COUNTER=y
CONFIG_SNTP=y
CONFIG_SNTP_LOG_LEVEL_DBG=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="pool.ntp.org"
CONFIG_NET_CONFIG_SNTP_INIT_SERVER_USE_DHCPV4_OPTION=y
CONFIG_NET_CONFIG_SNTP_INIT_RESYNC=y
CONFIG_NET_CONFIG_SNTP_INIT_RESYNC_ON_FAILURE_INTERVAL=15
CONFIG_NET_CONFIG_SNTP_INIT_USE_CONNECTION_MANAGER=y
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_CLOCK_SNTP_SET_RTC=y
CONFIG_NET_CONFIG_LOG_LEVEL_DBG=y

# Logging
CONFIG_LOG_BACKEND_SHOW_TIMESTAMP=y
CONFIG_LOG_OUTPUT_FORMAT_DATE_TIMESTAMP=y
CONFIG_LOG_TIMESTAMP_USE_REALTIME=y
