# USB device
CONFIG_USB_DEVICE_STACK_NEXT=y

CONFIG_SAMPLE_USBD_MANUFACTURER="Techleef"
CONFIG_SAMPLE_USBD_PRODUCT="ColdTracker"
CONFIG_SAMPLE_USBD_PID=0x0001

# CDC NCM Ethernet
CONFIG_NET_L2_ETHERNET=y

# Networking starts after the USB device is enabled
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_DHCPV4=y

# Keep USB logs quiet
CONFIG_USBD_CDC_NCM_LOG_LEVEL_WRN=y
CONFIG_USBD_LOG_LEVEL_WRN=y
