# Disable USB NCM for this experiment
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_NET_DHCPV4=n

# PPP over UART
CONFIG_NET_DRIVERS=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_PPP=y
CONFIG_NET_DEFAULT_IF_PPP=y
CONFIG_NET_L2_PPP_OPTION_DNS_USE=y

# USART1 belongs entirely to PPP
CONFIG_UART_CONSOLE=n
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NET_PPP_ASYNC_UART=n

CONFIG_NET_PPP_UART_BUF_LEN=128
CONFIG_NET_PPP_RINGBUF_SIZE=2048
CONFIG_NET_PPP_RX_STACK_SIZE=2048
