# OTA
CONFIG_IMG_MANAGER=y
CONFIG_IMG_BLOCK_BUF_SIZE=512
CONFIG_IMG_ENABLE_IMAGE_CHECK=y
CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_MCUBOOT_SHELL=y

# Flash
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_STREAM_FLASH=y
