# Disable USB NCM for this experiment
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_NET_DHCPV4=n

# PPP over UART
CONFIG_NET_DRIVERS=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_PPP=y
CONFIG_NET_DEFAULT_IF_PPP=y

# USART1 belongs entirely to PPP
CONFIG_UART_CONSOLE=n
CONFIG_SHELL_BACKEND_SERIAL=n
