manifest:
  version: 0.7

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

    - name: servz
      url-base: https://github.com/bayrem-gharsellaoui

  projects:
    - name: zephyr
      repo-path: zephyr
      revision: main
      path: zephyr
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_espressif
          - mcuboot
          - mbedtls
          - tf-psa-crypto
          - segger

    - name: servz
      remote: servz
      revision: main
      path: modules/servz

  self:
    path: application
