# Wi-Fi
CONFIG_WIFI=y

# Credentials
CONFIG_WIFI_CREDENTIALS_STATIC=y
CONFIG_WIFI_CREDENTIALS_STATIC_SSID="F3D3 Hyperoptic 1Gb Fibre 2.4Ghz"
CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="6puYZJG5f63D"
CONFIG_WIFI_CREDENTIALS_STATIC_TYPE_PSK=y

# Networking
CONFIG_NET_DHCPV4=y
