# Binary name
CONFIG_KERNEL_BIN_NAME="coldtracker-native_sim"

# Shell on stdin/stdout
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_LOG_RUNTIME_DEFAULT_LEVEL=4

# Native socket offload
CONFIG_ETH_NATIVE_TAP=n
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y

# Give Zephyr's logical interface an IPv4 address
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
