# SEGGER RTT transport
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096

# Shell over RTT
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_RTT=y
CONFIG_SHELL_BACKEND_SERIAL=n

# Send Zephyr logs through the shell backend.
# This gives us logs + interactive shell in the same RTT terminal.
CONFIG_SHELL_LOG_BACKEND=y

# Redirect printk() through the logging subsystem as well.
CONFIG_LOG_PRINTK=y

# Disable standalone logging backends.
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_SWO=n
