# Network variant binary name
CONFIG_KERNEL_BIN_NAME="coldtracker-xiao_esp32c3-net-wifi"

# ESP32 Wi-Fi driver
CONFIG_WIFI_ESP32=y

# Stack sizes
CONFIG_NET_TCP_WORKQ_STACK_SIZE=4096
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096
CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=4096
CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=4096
