# Network variant binary name
CONFIG_KERNEL_BIN_NAME="coldtracker-native_sim-net-nsos"

# Give Zephyr's logical interface an IPv4 address
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
