name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [nucleo_u575zi_q, xiao_esp32c3]

    steps:
      - name: Checkout module repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          manifest-file-name: west.yml
          toolchains: arm-zephyr-eabi:xtensa-espressif_esp32_zephyr-elf

      - name: Build on native_sim (without OTA)
        run: |
          west build -b native_sim -p

      - name: Build both application and mcuboot on ${{ matrix.board }}
        run: |
          west build -b ${{ matrix.board }} -p --sysbuild -- -DEXTRA_CONF_FILE=overlay-ota.conf
