name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - native_sim
          - nucleo_u575zi_q
          - xiao_esp32c3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: application

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Zephyr environment
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: application
          toolchains: arm-zephyr-eabi:riscv64-zephyr-elf

      - name: Fetch ESP32 binary blobs
        if: matrix.board == 'xiao_esp32c3'
        run: west blobs fetch hal_espressif

      - name: Build native
        if: matrix.board == 'native_sim'
        working-directory: application
        run: |
          west build -b ${{ matrix.board }} -p

      - name: Build hardware
        if: matrix.board != 'native_sim'
        working-directory: application
        run: |
          west build -b ${{ matrix.board }} -p --sysbuild -- -DEXTRA_CONF_FILE=overlay-ota.conf
